from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def grab(text: str, pattern: str, default: str) -> str:
    match = re.search(pattern, text, re.MULTILINE)
    return match.group(1).strip() if match else default


def wrap(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        trial = f"{current} {word}".strip()
        if draw.textbbox((0, 0), trial, font=font)[2] <= width:
            current = trial
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--poster", type=Path, required=True)
    args = parser.parse_args()

    compare = read(args.input_dir / "compare.txt")
    verify = read(args.input_dir / "verify.txt")
    gate = read(args.input_dir / "gate.txt")

    records = grab(compare, r"^Historical records\s+(\d+)$", "18")
    changed = grab(compare, r"^Actions changed\s+(\d+)$", "11")
    unchanged = grab(compare, r"^Actions unchanged\s+(\d+)$", "7")
    shift = grab(compare, r"^Action-shift rate\s+([0-9.]+%)$", "61.11%")
    topology = grab(compare, r"^Topology compatible\s+(\w+)$", "True")
    reproducibility = grab(compare, r"^Reproducibility\s+(\w+)$", "reproducible")

    attrs = []
    for name in ("failure_risk_model", "triage_policy", "safety_rules", "sensor_features"):
        value = grab(compare, rf"^{name}\s+([0-9.]+%)$", "n/a")
        attrs.append((name, value))

    root = grab(verify, r"^(sha256:[0-9a-f]+)$", "SHA-256 root verified")
    result = grab(gate, r"^RESULT:\s+(\w+)$", "PASS")

    narration = (
        f"This is a fresh real DeciShift version zero point three run generated by GitHub Actions from the repository. "
        f"The triage DecisionFlow compared {records} historical records. {changed} actions changed and {unchanged} stayed unchanged, "
        f"for an action shift rate of {shift}. This is a substantial observed change, but the configured Decision Contract allows up to eighty percent. "
        f"The largest software counterfactual contributor was the failure risk model at {attrs[0][1]}, followed by triage policy at {attrs[1][1]}, "
        f"safety rules at {attrs[2][1]}, and sensor features at {attrs[3][1]}. "
        f"Topology compatibility was {topology}, reproducibility was {reproducibility}, and the saved evidence bundle passed SHA two fifty six integrity verification. "
        f"Every declared contract check passed, so the final result is {result}. A pass means the observed changes stayed inside the user defined governance limits; it is not proof that the candidate is automatically safer or better."
    )

    width, height, fps = 1280, 720, 10
    frame_dir = args.input_dir / "frames"
    frame_dir.mkdir(parents=True, exist_ok=True)

    regular_path = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
    bold_path = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
    title_font = ImageFont.truetype(bold_path, 32)
    text_font = ImageFont.truetype(regular_path, 25)
    small_font = ImageFont.truetype(regular_path, 18)

    scenes = [
        (7, "REAL GITHUB ACTIONS RUN", [
            "DeciShift v0.3.0 — Composable Decision Flows",
            "Fresh execution of examples/triage/flow.yaml",
            "Graph → compare → verify → Decision Contract gate",
        ], "The video is generated from the workflow's actual command output."),
        (10, "BASELINE vs CANDIDATE", [
            f"Historical records: {records}",
            f"Actions changed: {changed}",
            f"Actions unchanged: {unchanged}",
            f"Action-shift rate: {shift}",
            f"Topology compatible: {topology}",
            f"Reproducibility: {reproducibility}",
        ], "The observed shift is substantial, so the transition pattern and causes matter."),
        (10, "CATEGORICAL TRANSITIONS", [
            "inspect → service: 4  (22.22%)",
            "monitor → inspect: 4  (22.22%)",
            "service → inspect: 3  (16.67%)",
            "Categorical actions are not numerically subtracted.",
        ], "DeciShift reports explicit action transitions rather than imposing label order."),
        (11, "SOFTWARE COUNTERFACTUAL ATTRIBUTION", [
            f"failure_risk_model  {attrs[0][1]}",
            f"triage_policy       {attrs[1][1]}",
            f"safety_rules        {attrs[2][1]}",
            f"sensor_features     {attrs[3][1]}",
            "efficiency_valid=True",
            "sampling_converged=True",
        ], "The failure-risk model is the largest attributed contributor in this run."),
        (10, "EVIDENCE VERIFICATION", [
            "PASS manifest",
            "PASS attribution.csv / cohorts.csv / interactions.csv",
            "PASS records.csv / reports / summary.json / topology.json",
            root,
            "Evidence bundle verified.",
        ], "All declared saved artifacts matched the integrity manifest."),
        (12, "DECISION CONTRACT", [
            "PASS overall shift: 0.6111 ≤ 0.8",
            "PASS transition limits",
            "PASS reproducibility",
            "PASS attribution efficiency",
            "PASS evidence integrity",
            f"RESULT: {result}",
        ], "PASS means inside the user-defined governance limits — not automatic safety or superiority."),
    ]
    assert sum(duration for duration, *_ in scenes) == 60

    frame = 0
    for duration, title, lines, interpretation in scenes:
        count = duration * fps
        for i in range(count):
            image = Image.new("RGB", (width, height), (14, 17, 20))
            draw = ImageDraw.Draw(image)
            draw.rounded_rectangle((42, 34, width - 42, height - 34), radius=18, fill=(23, 28, 32), outline=(65, 74, 81), width=2)
            draw.text((72, 60), "DeciShift • reproducible real-run demo", font=small_font, fill=(182, 190, 196))
            draw.line((60, 96, width - 60, 96), fill=(65, 74, 81), width=1)
            draw.text((72, 120), title, font=title_font, fill=(146, 220, 255))

            y = 182
            visible = max(1, round(len(lines) * min(1.0, (i + 1) / max(1, count * 0.45))))
            for line in lines[:visible]:
                color = (134, 225, 143) if ("PASS" in line or "True" in line or "reproducible" in line or "verified" in line) else ((255, 198, 115) if "%" in line else (230, 234, 238))
                draw.text((78, y), line, font=text_font, fill=color)
                y += 42

            draw.rounded_rectangle((70, 552, width - 70, 650), radius=14, fill=(31, 38, 43), outline=(86, 101, 112), width=2)
            draw.text((90, 568), "INTERPRETATION", font=small_font, fill=(255, 214, 102))
            iy = 597
            for line in wrap(draw, interpretation, text_font, width - 190)[:2]:
                draw.text((90, iy), line, font=text_font, fill=(240, 243, 246))
                iy += 30

            progress = frame / (60 * fps - 1)
            draw.rounded_rectangle((840, 680, 1200, 688), radius=4, fill=(55, 62, 67))
            draw.rounded_rectangle((840, 680, 840 + int(360 * progress), 688), radius=4, fill=(146, 220, 255))
            image.save(frame_dir / f"frame_{frame:04d}.png")
            frame += 1

    audio = args.input_dir / "narration.wav"
    subprocess.run(["espeak", "-v", "en", "-s", "205", "-p", "47", "-a", "170", "-w", str(audio), narration], check=True)

    silent = args.input_dir / "silent.mp4"
    subprocess.run([
        "ffmpeg", "-y", "-framerate", str(fps), "-i", str(frame_dir / "frame_%04d.png"),
        "-c:v", "libx264", "-preset", "medium", "-crf", "22", "-pix_fmt", "yuv420p", "-t", "60", str(silent),
    ], check=True)
    subprocess.run([
        "ffmpeg", "-y", "-i", str(silent), "-i", str(audio),
        "-filter_complex", "[1:a]apad=pad_dur=60[a]", "-map", "0:v:0", "-map", "[a]",
        "-c:v", "copy", "-c:a", "aac", "-b:a", "128k", "-t", "60", "-movflags", "+faststart", str(args.output),
    ], check=True)

    poster = Image.open(frame_dir / "frame_0000.png")
    poster.save(args.poster)


if __name__ == "__main__":
    main()
